<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AffiliateProgramSeeder extends Seeder
{
    public function run(): void
    {
        $programs = [
            // ── ASSURANCES INTERNATIONALES ───────────────────────────────────
            [
                'category' => 'insurance',
                'name' => 'SafetyWing',
                'website_url' => 'https://safetywing.com',
                'affiliate_dashboard_url' => 'https://safetywing.com/ambassador',
                'affiliate_signup_url' => 'https://safetywing.com/ambassador',
                'commission_type' => 'recurring',
                'commission_info' => '10% récurrent sur les renouvellements',
                'payout_threshold' => 100.00,
                'payout_method' => 'paypal',
                'payout_frequency' => 'monthly',
                'network' => 'Direct',
                'description' => 'Assurance voyage/nomade pour expats et digital nomads',
            ],
            [
                'category' => 'insurance',
                'name' => 'World Nomads',
                'website_url' => 'https://www.worldnomads.com',
                'affiliate_dashboard_url' => 'https://www.cj.com',
                'affiliate_signup_url' => 'https://www.cj.com/advertiser/world-nomads',
                'commission_type' => 'percentage',
                'commission_info' => '10% par vente via CJ Affiliate',
                'payout_threshold' => 50.00,
                'payout_method' => 'bank',
                'payout_frequency' => 'monthly',
                'network' => 'CJ Affiliate',
                'description' => 'Assurance voyage flexible pour backpackers et aventuriers',
            ],
            [
                'category' => 'insurance',
                'name' => 'Cigna Global Health',
                'website_url' => 'https://www.cigna.com/global',
                'affiliate_dashboard_url' => 'https://www.cignahealthbenefits.com/en/affiliates',
                'affiliate_signup_url' => 'https://www.cignahealthbenefits.com/en/affiliates',
                'commission_type' => 'fixed_per_lead',
                'commission_info' => 'Commission sur lead qualifié',
                'payout_threshold' => 100.00,
                'payout_method' => 'bank',
                'payout_frequency' => 'monthly',
                'network' => 'Direct',
                'description' => 'Assurance santé internationale premium pour expats',
            ],
            [
                'category' => 'insurance',
                'name' => 'AXA Expat',
                'website_url' => 'https://www.axa-expatriate.com',
                'affiliate_signup_url' => 'https://www.axa-expatriate.com/affiliation',
                'commission_type' => 'percentage',
                'commission_info' => '~15% commission',
                'payout_method' => 'bank',
                'payout_frequency' => 'monthly',
                'network' => 'Direct',
                'description' => 'Assurance santé et rapatriement pour expatriés AXA',
            ],
            [
                'category' => 'insurance',
                'name' => 'Allianz Care',
                'website_url' => 'https://www.allianzcare.com',
                'affiliate_signup_url' => 'https://www.allianzcare.com/en/business-partners/become-a-partner.html',
                'commission_type' => 'percentage',
                'commission_info' => 'Commission variable selon produit',
                'network' => 'Direct',
                'description' => 'Assurance santé internationale Allianz pour entreprises et particuliers',
            ],
            [
                'category' => 'insurance',
                'name' => 'iHi Bupa',
                'website_url' => 'https://www.ihi.com',
                'affiliate_signup_url' => 'https://www.ihi.com/affiliates',
                'commission_type' => 'percentage',
                'commission_info' => 'Jusqu\'à 25% commission',
                'network' => 'Direct',
                'description' => 'Plans de santé internationaux Bupa pour expats',
            ],
            [
                'category' => 'insurance',
                'name' => 'Heymondo',
                'website_url' => 'https://heymondo.com',
                'affiliate_signup_url' => 'https://heymondo.com/affiliates',
                'commission_type' => 'percentage',
                'commission_info' => '20% commission',
                'payout_threshold' => 50.00,
                'payout_method' => 'paypal',
                'network' => 'Direct',
                'description' => 'Assurance voyage avec app mobile et assistance 24/7',
            ],

            // ── FINANCE & TRANSFERTS D\'ARGENT ───────────────────────────────
            [
                'category' => 'finance',
                'name' => 'Wise (TransferWise)',
                'website_url' => 'https://wise.com',
                'affiliate_dashboard_url' => 'https://wise.com/partners',
                'affiliate_signup_url' => 'https://wise.com/partners',
                'commission_type' => 'fixed_per_sale',
                'commission_info' => '£50 par utilisateur après transfert de £500+',
                'payout_threshold' => 50.00,
                'payout_method' => 'bank',
                'payout_frequency' => 'monthly',
                'network' => 'Direct',
                'description' => 'Transferts d\'argent internationaux à frais réels',
            ],
            [
                'category' => 'finance',
                'name' => 'Revolut',
                'website_url' => 'https://www.revolut.com',
                'affiliate_dashboard_url' => 'https://www.revolut.com/affiliate',
                'affiliate_signup_url' => 'https://www.revolut.com/affiliate',
                'commission_type' => 'fixed_per_lead',
                'commission_info' => 'Commission sur comptes Premium activés',
                'network' => 'Direct / Impact',
                'description' => 'Banque digitale internationale sans frais cachés',
            ],
            [
                'category' => 'finance',
                'name' => 'N26',
                'website_url' => 'https://n26.com',
                'affiliate_signup_url' => 'https://n26.com/affiliates',
                'commission_type' => 'fixed_per_lead',
                'commission_info' => 'Commission par compte ouvert',
                'network' => 'Direct',
                'description' => 'Banque mobile européenne pour expats',
            ],
            [
                'category' => 'finance',
                'name' => 'Remitly',
                'website_url' => 'https://www.remitly.com',
                'affiliate_signup_url' => 'https://www.remitly.com/affiliates',
                'commission_type' => 'fixed_per_sale',
                'commission_info' => '$20 par premier transfert',
                'payout_method' => 'paypal',
                'network' => 'Direct / CJ',
                'description' => 'Transferts d\'argent vers les pays en développement',
            ],
            [
                'category' => 'finance',
                'name' => 'WorldRemit',
                'website_url' => 'https://www.worldremit.com',
                'affiliate_signup_url' => 'https://www.worldremit.com/en/affiliates',
                'commission_type' => 'fixed_per_sale',
                'commission_info' => 'Commission par transfert effectué',
                'network' => 'Rakuten / Direct',
                'description' => 'Envois d\'argent international rapide et sécurisé',
            ],
            [
                'category' => 'finance',
                'name' => 'Paysend',
                'website_url' => 'https://paysend.com',
                'affiliate_signup_url' => 'https://paysend.com/affiliates',
                'commission_type' => 'fixed_per_sale',
                'commission_info' => '£5 par parrainage',
                'network' => 'Direct',
                'description' => 'Transferts d\'argent internationaux à tarif fixe',
            ],
            [
                'category' => 'finance',
                'name' => 'XE Money Transfer',
                'website_url' => 'https://www.xe.com',
                'affiliate_signup_url' => 'https://www.xe.com/affiliates/',
                'commission_type' => 'percentage',
                'commission_info' => 'Commission sur les spreads',
                'network' => 'Impact',
                'description' => 'Transferts de devises et taux de change',
            ],

            // ── VOYAGE & HÉBERGEMENT ─────────────────────────────────────────
            [
                'category' => 'travel',
                'name' => 'Booking.com',
                'website_url' => 'https://www.booking.com',
                'affiliate_dashboard_url' => 'https://www.booking.com/affiliate-program/index.html',
                'affiliate_signup_url' => 'https://www.booking.com/affiliate-program/index.html',
                'commission_type' => 'percentage',
                'commission_info' => '25-40% de la commission Booking',
                'payout_threshold' => 100.00,
                'payout_method' => 'bank',
                'payout_frequency' => 'monthly',
                'network' => 'Direct',
                'description' => 'Hébergements hôtels, appartements, villas dans le monde',
            ],
            [
                'category' => 'travel',
                'name' => 'Airbnb',
                'website_url' => 'https://www.airbnb.com',
                'affiliate_signup_url' => 'https://www.airbnb.com/associates',
                'commission_type' => 'fixed_per_lead',
                'commission_info' => '$75 par hôte parrainé (après 1 réservation)',
                'payout_method' => 'paypal',
                'network' => 'Direct',
                'description' => 'Location courte/longue durée chez l\'habitant',
            ],
            [
                'category' => 'travel',
                'name' => 'Skyscanner',
                'website_url' => 'https://www.skyscanner.com',
                'affiliate_signup_url' => 'https://www.skyscanner.net/affiliates',
                'commission_type' => 'cpc',
                'commission_info' => 'CPC sur clics/vols réservés',
                'network' => 'CJ / Direct',
                'description' => 'Comparateur de vols internationaux',
            ],
            [
                'category' => 'travel',
                'name' => 'Kiwi.com',
                'website_url' => 'https://www.kiwi.com',
                'affiliate_signup_url' => 'https://www.kiwi.com/en/partner',
                'commission_type' => 'percentage',
                'commission_info' => '3% sur chaque réservation',
                'network' => 'Direct',
                'description' => 'Comparateur de vols avec combinaisons créatives',
            ],
            [
                'category' => 'travel',
                'name' => 'HousingAnywhere',
                'website_url' => 'https://housinganywhere.com',
                'affiliate_signup_url' => 'https://housinganywhere.com/affiliates',
                'commission_type' => 'fixed_per_sale',
                'commission_info' => 'Commission par location conclue',
                'network' => 'Direct',
                'description' => 'Logements longue durée pour étudiants et jeunes expats',
            ],
            [
                'category' => 'travel',
                'name' => 'Spotahome',
                'website_url' => 'https://www.spotahome.com',
                'affiliate_signup_url' => 'https://www.spotahome.com/affiliates',
                'commission_type' => 'percentage',
                'commission_info' => 'Commission sur réservations longue durée',
                'network' => 'Direct',
                'description' => 'Appartements longue durée pour expats en Europe',
            ],
            [
                'category' => 'travel',
                'name' => 'Rentalcars.com',
                'website_url' => 'https://www.rentalcars.com',
                'affiliate_signup_url' => 'https://www.rentalcars.com/affiliates',
                'commission_type' => 'percentage',
                'commission_info' => '5-7% par location',
                'network' => 'Rentalcars Partner Program',
                'description' => 'Location de voiture internationale dans 160 pays',
            ],

            // ── VPN ──────────────────────────────────────────────────────────
            [
                'category' => 'vpn',
                'name' => 'NordVPN',
                'website_url' => 'https://nordvpn.com',
                'affiliate_dashboard_url' => 'https://nordvpn.com/affiliates/',
                'affiliate_signup_url' => 'https://nordvpn.com/affiliates/',
                'commission_type' => 'hybrid',
                'commission_info' => '40-100% première vente + 30% récurrent',
                'payout_threshold' => 10.00,
                'payout_method' => 'paypal',
                'payout_frequency' => 'monthly',
                'network' => 'Direct / Impact',
                'description' => 'VPN premium indispensable pour les expats',
            ],
            [
                'category' => 'vpn',
                'name' => 'ExpressVPN',
                'website_url' => 'https://www.expressvpn.com',
                'affiliate_signup_url' => 'https://www.expressvpn.com/affiliate',
                'commission_type' => 'fixed_per_sale',
                'commission_info' => '$13-36 par abonnement vendu',
                'payout_method' => 'paypal',
                'payout_frequency' => 'monthly',
                'network' => 'Direct / CJ',
                'description' => 'VPN rapide avec serveurs dans 94 pays',
            ],
            [
                'category' => 'vpn',
                'name' => 'Surfshark',
                'website_url' => 'https://surfshark.com',
                'affiliate_signup_url' => 'https://surfshark.com/affiliates',
                'commission_type' => 'hybrid',
                'commission_info' => '40% + 40% récurrent',
                'payout_method' => 'paypal',
                'network' => 'Direct / Impact',
                'description' => 'VPN économique avec appareils illimités',
            ],

            // ── DÉMÉNAGEMENT ─────────────────────────────────────────────────
            [
                'category' => 'housing',
                'name' => 'Sirelo',
                'website_url' => 'https://www.sirelo.com',
                'affiliate_signup_url' => 'https://www.sirelo.com/affiliate',
                'commission_type' => 'fixed_per_lead',
                'commission_info' => 'Commission par demande de devis',
                'network' => 'Direct',
                'description' => 'Comparateur de déménagements internationaux',
            ],
            [
                'category' => 'housing',
                'name' => 'MoveHub',
                'website_url' => 'https://www.movehub.com',
                'affiliate_signup_url' => 'https://www.movehub.com/affiliates',
                'commission_type' => 'fixed_per_lead',
                'commission_info' => 'Commission par lead qualifié déménagement',
                'network' => 'Direct',
                'description' => 'Guides et comparateurs pour déménagement international',
            ],

            // ── EMPLOI & RECRUTEMENT ─────────────────────────────────────────
            [
                'category' => 'employment',
                'name' => 'LinkedIn Premium',
                'website_url' => 'https://www.linkedin.com',
                'affiliate_signup_url' => 'https://www.linkedin.com/help/linkedin/ask/TS-NAEP',
                'commission_type' => 'percentage',
                'commission_info' => '35% sur Premium via Impact',
                'network' => 'Impact',
                'description' => 'Réseau professionnel et offres d\'emploi international',
            ],

            // ── FORMATION & LANGUES ──────────────────────────────────────────
            [
                'category' => 'education',
                'name' => 'Babbel',
                'website_url' => 'https://www.babbel.com',
                'affiliate_signup_url' => 'https://www.babbel.com/affiliates',
                'commission_type' => 'percentage',
                'commission_info' => '20-25% par abonnement',
                'payout_method' => 'paypal',
                'network' => 'CJ Affiliate',
                'description' => 'Apprentissage des langues adapté aux expats',
            ],
            [
                'category' => 'education',
                'name' => 'Preply',
                'website_url' => 'https://preply.com',
                'affiliate_signup_url' => 'https://preply.com/en/affiliate-program',
                'commission_type' => 'percentage',
                'commission_info' => '30% commission 1ère leçon',
                'payout_method' => 'paypal',
                'network' => 'Direct',
                'description' => 'Cours de langues en ligne avec tuteurs natifs',
            ],
            [
                'category' => 'education',
                'name' => 'Coursera',
                'website_url' => 'https://www.coursera.org',
                'affiliate_signup_url' => 'https://www.coursera.org/about/affiliates',
                'commission_type' => 'percentage',
                'commission_info' => '10-45% selon le produit',
                'network' => 'Rakuten / LinkShare',
                'description' => 'Formations en ligne certifiées pour reconversion professionnelle',
            ],
            [
                'category' => 'education',
                'name' => 'Udemy',
                'website_url' => 'https://www.udemy.com',
                'affiliate_signup_url' => 'https://www.udemy.com/affiliate/',
                'commission_type' => 'percentage',
                'commission_info' => '15% par cours acheté',
                'network' => 'Impact',
                'description' => 'Cours en ligne dans tous les domaines',
            ],

            // ── SHOPPING ─────────────────────────────────────────────────────
            [
                'category' => 'shopping',
                'name' => 'Amazon France',
                'website_url' => 'https://www.amazon.fr',
                'affiliate_dashboard_url' => 'https://partenaires.amazon.fr',
                'affiliate_signup_url' => 'https://partenaires.amazon.fr',
                'commission_type' => 'percentage',
                'commission_info' => '3-10% selon catégorie',
                'payout_threshold' => 25.00,
                'payout_method' => 'bank',
                'payout_frequency' => 'monthly',
                'network' => 'Amazon Associates',
                'description' => 'Amazon FR — produits pour installation/déménagement',
            ],
            [
                'category' => 'shopping',
                'name' => 'Amazon UK',
                'website_url' => 'https://www.amazon.co.uk',
                'affiliate_signup_url' => 'https://affiliate-program.amazon.co.uk',
                'commission_type' => 'percentage',
                'commission_info' => '3-10% selon catégorie',
                'network' => 'Amazon Associates',
                'description' => 'Amazon UK — essentiel pour expats en Grande-Bretagne',
            ],
            [
                'category' => 'shopping',
                'name' => 'Amazon Allemagne',
                'website_url' => 'https://www.amazon.de',
                'affiliate_signup_url' => 'https://partnernet.amazon.de',
                'commission_type' => 'percentage',
                'commission_info' => '3-10% selon catégorie',
                'network' => 'Amazon Associates',
                'description' => 'Amazon DE — pour expats en Allemagne/Autriche',
            ],

            // ── TÉLÉCOM & CONNECTIVITÉ ───────────────────────────────────────
            [
                'category' => 'telecom',
                'name' => 'Airalo (eSIM)',
                'website_url' => 'https://www.airalo.com',
                'affiliate_signup_url' => 'https://www.airalo.com/affiliate-program',
                'commission_type' => 'percentage',
                'commission_info' => '8% par vente d\'eSIM',
                'payout_method' => 'paypal',
                'payout_frequency' => 'monthly',
                'network' => 'Direct',
                'description' => 'eSIM pour voyager connecté dans 190+ pays',
            ],
            [
                'category' => 'telecom',
                'name' => 'Holafly (eSIM)',
                'website_url' => 'https://esim.holafly.com',
                'affiliate_signup_url' => 'https://esim.holafly.com/affiliates',
                'commission_type' => 'percentage',
                'commission_info' => '10% par vente',
                'payout_method' => 'paypal',
                'network' => 'Direct',
                'description' => 'eSIM data illimité pour les voyageurs',
            ],
            [
                'category' => 'telecom',
                'name' => 'SimOptions',
                'website_url' => 'https://simoptions.com',
                'affiliate_signup_url' => 'https://simoptions.com/affiliates',
                'commission_type' => 'percentage',
                'commission_info' => 'Commission sur ventes SIM internationales',
                'network' => 'Direct',
                'description' => 'Cartes SIM prépayées pour 200+ pays',
            ],

            // ── COMMUNAUTÉS EXPATS ───────────────────────────────────────────
            [
                'category' => 'community',
                'name' => 'Expat.com',
                'website_url' => 'https://www.expat.com',
                'affiliate_signup_url' => 'https://www.expat.com/en/affiliate/',
                'commission_type' => 'percentage',
                'commission_info' => 'Commission sur abonnements premium',
                'network' => 'Direct',
                'description' => 'Plus grand réseau d\'expatriés mondial',
            ],
            [
                'category' => 'community',
                'name' => 'InterNations',
                'website_url' => 'https://www.internations.org',
                'affiliate_signup_url' => 'https://www.internations.org/partner',
                'commission_type' => 'fixed_per_lead',
                'commission_info' => 'Commission par inscription Albatross',
                'network' => 'Direct',
                'description' => 'Réseau social pour expatriés dans 420 villes',
            ],
            [
                'category' => 'community',
                'name' => 'Meetup',
                'website_url' => 'https://www.meetup.com',
                'affiliate_signup_url' => 'https://www.meetup.com/affiliates/',
                'commission_type' => 'percentage',
                'commission_info' => 'Commission sur abonnements Pro',
                'network' => 'CJ Affiliate',
                'description' => 'Communautés locales pour trouver des expats dans sa ville',
            ],

            // ── JURIDIQUE & ADMINISTRATIF ─────────────────────────────────────
            [
                'category' => 'legal',
                'name' => 'HelloSign (Dropbox)',
                'website_url' => 'https://www.hellosign.com',
                'affiliate_signup_url' => 'https://www.hellosign.com/info/reseller-affiliate-program',
                'commission_type' => 'percentage',
                'commission_info' => '15-20% sur abonnements',
                'network' => 'Direct',
                'description' => 'Signature électronique pour documents légaux',
            ],
            [
                'category' => 'legal',
                'name' => 'iGolder (Notarisation)',
                'website_url' => 'https://www.apostille.net',
                'affiliate_signup_url' => null,
                'commission_type' => 'unknown',
                'commission_info' => 'À vérifier',
                'network' => 'Direct',
                'description' => 'Services de légalisation et apostille de documents',
            ],

            // ── SERVICES PRATIQUES ────────────────────────────────────────────
            [
                'category' => 'other',
                'name' => 'Mailbox (Anytime Mailbox)',
                'website_url' => 'https://www.anytimemailbox.com',
                'affiliate_signup_url' => 'https://www.anytimemailbox.com/affiliates',
                'commission_type' => 'recurring',
                'commission_info' => '20% récurrent sur abonnements',
                'network' => 'Direct',
                'description' => 'Adresse postale virtuelle pour expats sans domicile fixe',
            ],
            [
                'category' => 'other',
                'name' => 'Printify (POD)',
                'website_url' => 'https://printify.com',
                'affiliate_signup_url' => 'https://printify.com/affiliates/',
                'commission_type' => 'recurring',
                'commission_info' => '5% récurrent pendant 12 mois',
                'network' => 'Direct',
                'description' => 'Print-on-demand pour créer des produits personnalisés',
            ],
        ];

        $now = now();
        foreach ($programs as $i => $program) {
            DB::table('affiliate_programs')->insertOrIgnore([
                'name'                   => $program['name'],
                'slug'                   => Str::slug($program['name']),
                'category'               => $program['category'],
                'description'            => $program['description'] ?? null,
                'website_url'            => $program['website_url'],
                'affiliate_dashboard_url'=> $program['affiliate_dashboard_url'] ?? null,
                'affiliate_signup_url'   => $program['affiliate_signup_url'] ?? null,
                'my_affiliate_link'      => null,
                'commission_type'        => $program['commission_type'],
                'commission_info'        => $program['commission_info'] ?? null,
                'cookie_duration_days'   => $program['cookie_duration_days'] ?? null,
                'payout_threshold'       => $program['payout_threshold'] ?? null,
                'payout_method'          => $program['payout_method'] ?? null,
                'payout_frequency'       => $program['payout_frequency'] ?? null,
                'current_balance'        => 0,
                'total_earned'           => 0,
                'last_payout_amount'     => null,
                'last_payout_at'         => null,
                'status'                 => 'not_applied',
                'network'                => $program['network'] ?? null,
                'logo_url'               => null,
                'notes'                  => null,
                'sort_order'             => $i,
                'created_at'             => $now,
                'updated_at'             => $now,
            ]);
        }
    }
}
