<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Long-tail keywords with search intent classification.
 *
 * Each keyword has 4+ words and a classified intent that determines
 * the content FORMAT generated by ArticleGenerationService.
 *
 * Intents: informational, commercial_investigation, transactional, local, urgency
 */
class LongTailKeywordsSeeder extends Seeder
{
    public function run(): void
    {
        $keywords = [
            // ══════════════════════════════════════════
            // INFORMATIONAL — l'utilisateur veut APPRENDRE
            // ══════════════════════════════════════════
            ['comment obtenir un visa digital nomad en Espagne en 2026', 'informational', 'visa', 'ES'],
            ['difference entre visa long sejour et carte de sejour en France', 'informational', 'visa', 'FR'],
            ['comment fonctionne la CFE pour les expatries francais', 'informational', 'fiscalite', null],
            ['regle des 183 jours residence fiscale expliquee simplement', 'informational', 'fiscalite', null],
            ['comment ouvrir un compte bancaire au Portugal sans NIE', 'informational', 'finance', 'PT'],
            ['quelles sont les demarches pour s installer au Canada en famille', 'informational', 'expatriation', 'CA'],
            ['comment inscrire ses enfants dans une ecole internationale a Dubai', 'informational', 'education', 'AE'],
            ['droits des travailleurs etrangers en Allemagne contrat de travail', 'informational', 'juridique', 'DE'],
            ['comment declarer ses impots quand on est expatrie en Thailande', 'informational', 'fiscalite', 'TH'],
            ['reconnaissance diplome francais a l etranger procedure 2026', 'informational', 'education', null],
            ['comment obtenir la nationalite portugaise par investissement', 'informational', 'visa', 'PT'],
            ['systeme de sante au Japon pour les expatries comment ca marche', 'informational', 'sante', 'JP'],
            ['conge maternite expatriee quels sont mes droits', 'informational', 'juridique', null],
            ['double imposition France Espagne convention fiscale 2026', 'informational', 'fiscalite', 'ES'],
            ['comment voter depuis l etranger en tant qu expatrie francais', 'informational', 'demarches', null],
            ['pvt canada conditions age limite et demarches completes', 'informational', 'visa', 'CA'],
            ['freelance en Estonie e-residency avantages et inconvenients', 'informational', 'entrepreneuriat', 'EE'],
            ['comment transferer sa retraite francaise a l etranger', 'informational', 'retraite', null],
            ['assurance rapatriement comment ca fonctionne et quand l utiliser', 'informational', 'assurance', null],
            ['comment trouver un logement a distance avant son expatriation', 'informational', 'logement', null],
            ['choc culturel expatriation etapes et comment le surmonter', 'informational', 'quotidien', null],
            ['scolarite enfant expatrie systeme francais ou international', 'informational', 'education', null],
            ['succession expatrie quelle loi s applique', 'informational', 'juridique', null],
            ['permis de conduire international validite et echange a l etranger', 'informational', 'transport', null],
            ['comment garder son numero de telephone francais a l etranger', 'informational', 'telecom', null],

            // ══════════════════════════════════════════
            // COMMERCIAL INVESTIGATION — l'utilisateur veut COMPARER
            // ══════════════════════════════════════════
            ['meilleure assurance sante expatrie pas cher 2026 comparatif', 'commercial_investigation', 'assurance', null],
            ['wise vs revolut pour expatrie lequel choisir en 2026', 'commercial_investigation', 'finance', null],
            ['meilleur vpn pour regarder la television francaise a l etranger', 'commercial_investigation', 'vpn', null],
            ['comparatif banques en ligne pour expatries sans frais 2026', 'commercial_investigation', 'finance', null],
            ['meilleure esim pour voyager dans plusieurs pays pas cher', 'commercial_investigation', 'telecom', null],
            ['assurance voyage longue duree moins de 50 euros par mois comparatif', 'commercial_investigation', 'assurance', null],
            ['meilleur pays pour prendre sa retraite en Europe pas cher', 'commercial_investigation', 'retraite', null],
            ['comparatif demenagement international prix et avis 2026', 'commercial_investigation', 'demenagement', null],
            ['meilleur pays pour digital nomad visa et cout de vie 2026', 'commercial_investigation', 'visa', null],
            ['safetywing vs world nomads quelle assurance digital nomad choisir', 'commercial_investigation', 'assurance', null],
            ['meilleure carte bancaire sans frais pour voyager en 2026', 'commercial_investigation', 'finance', null],
            ['portugal vs espagne pour la retraite comparatif complet', 'commercial_investigation', 'retraite', null],
            ['thailande vs vietnam cout de vie digital nomad comparatif', 'commercial_investigation', 'cout_vie', null],
            ['meilleures ecoles internationales en Asie du Sud Est classement', 'commercial_investigation', 'education', null],
            ['cfe ou assurance privee pour expatrie avantages inconvenients', 'commercial_investigation', 'assurance', null],

            // ══════════════════════════════════════════
            // TRANSACTIONAL — l'utilisateur veut AGIR
            // ══════════════════════════════════════════
            ['prendre rendez-vous avocat immigration en ligne pas cher', 'transactional', 'juridique', null],
            ['acheter assurance voyage expatrie en ligne depart immediat', 'transactional', 'assurance', null],
            ['ouvrir compte wise en ligne pour expatrie inscription rapide', 'transactional', 'finance', null],
            ['souscrire vpn pour l etranger abonnement mensuel pas cher', 'transactional', 'vpn', null],
            ['acheter esim internationale avant le depart en voyage', 'transactional', 'telecom', null],
            ['demander devis demenagement international en ligne gratuit', 'transactional', 'demenagement', null],
            ['inscrire consulat francais a l etranger en ligne', 'transactional', 'demarches', null],
            ['parler a un avocat francais en thailande rapidement', 'transactional', 'juridique', 'TH'],
            ['trouver expert local pour aider installation au Portugal', 'transactional', 'expatriation', 'PT'],
            ['acheter billet avion pas cher pour expatrie aller simple', 'transactional', 'voyage', null],

            // ══════════════════════════════════════════
            // LOCAL — l'utilisateur cherche un service DANS un lieu
            // ══════════════════════════════════════════
            ['avocat francais a Bangkok specialise immigration', 'local', 'juridique', 'TH'],
            ['medecin generaliste francophone a Lisbonne centre ville', 'local', 'sante', 'PT'],
            ['ecole francaise a Dubai inscription et tarifs 2026', 'local', 'education', 'AE'],
            ['notaire francophone a Barcelone pour achat immobilier', 'local', 'juridique', 'ES'],
            ['dentiste francophone a Montreal recommande par expatries', 'local', 'sante', 'CA'],
            ['comptable francais a Londres specialise expatries', 'local', 'fiscalite', 'GB'],
            ['agence immobiliere francophone a Berlin pour expatries', 'local', 'logement', 'DE'],
            ['psychologue francophone a Amsterdam pour expatries', 'local', 'sante', 'NL'],
            ['avocat droit du travail francophone a Geneve', 'local', 'juridique', 'CH'],
            ['pediatre francophone a Singapour pour famille expatriee', 'local', 'sante', 'SG'],
            ['garage automobile francophone a Casablanca pour expatries', 'local', 'transport', 'MA'],
            ['expert comptable francais a Luxembourg ville', 'local', 'fiscalite', 'LU'],

            // ══════════════════════════════════════════
            // URGENCY — l'utilisateur a un problème MAINTENANT
            // ══════════════════════════════════════════
            ['passeport francais vole en Thailande que faire en urgence', 'urgency', 'urgence', 'TH'],
            ['accident de voiture a l etranger procedure immediate', 'urgency', 'urgence', null],
            ['hospitalisation urgence a l etranger sans assurance que faire', 'urgency', 'urgence', null],
            ['arrete par la police au Mexique droits et demarches', 'urgency', 'urgence', 'MX'],
            ['perte carte bancaire a l etranger bloquer et remplacer', 'urgency', 'urgence', null],
            ['expulsion locataire expatrie droits et recours immediats', 'urgency', 'juridique', null],
            ['enfant malade en vacances a l etranger urgence pediatrique', 'urgency', 'urgence', null],
            ['vol de bagages a l aeroport a l etranger que faire', 'urgency', 'urgence', null],
            ['catastrophe naturelle a l etranger rapatriement comment faire', 'urgency', 'urgence', null],
            ['arnaque en ligne pendant un voyage a l etranger porter plainte', 'urgency', 'urgence', null],
            ['agression physique a l etranger porter plainte ambassade', 'urgency', 'urgence', null],
            ['intoxication alimentaire grave en voyage que faire immediatement', 'urgency', 'urgence', null],
        ];

        $now = now();
        $total = 0;

        foreach ($keywords as $item) {
            DB::table('keyword_tracking')->insertOrIgnore([
                'keyword' => $item[0],
                'type' => 'long_tail',
                'search_intent' => $item[1],
                'language' => 'fr',
                'country' => $item[3],
                'category' => $item[2],
                'search_volume_estimate' => 'medium',
                'difficulty_estimate' => 'low',
                'trend' => 'stable',
                'articles_using_count' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
            $total++;
        }

        $this->command?->info("Seeded {$total} long-tail keywords with search intent classification.");
    }
}
